# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  collection_path: 'ansible_collections'

jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python27:
          python.version: '2.7'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
    steps:
    - checkout: self
      path: $(collection_path)/$(Build.Repository.Name)
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - script: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install pycodestyle
        python -m pip install voluptuous
        python -m pip install pylint
        python -m pip install coverage==4.5.4
        python -m pip install yamllint
        python -m pip install ansible
        ansible --version
      displayName: 'Install Ansible'
    - script: |
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - script: ansible-test sanity --docker -v --python $(python.version)
      displayName: 'Run all sanity tests'
    - script: |
        ansible-test coverage erase
        ansible-test sanity --coverage
        ansible-test coverage xml
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'tests/output/coverage/*'
        testRunTitle: 'Publish Test Results'

#    - script: bash <(curl -s https://codecov.io/bash)
#      displayName: 'Upload to codecov.io'
