# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  collection_path: 'ansible_collections'

jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python27:
          python.version: '2.7'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
    steps:
    - checkout: self
      path: $(collection_path)/$(Build.Repository.Name)
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - script: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install pycodestyle
        python -m pip install voluptuous
        python -m pip install pylint
        python -m pip install coverage
        python -m pip install yamllint
        python -m pip install ansible
        ansible --version
      displayName: 'Install Ansible'
    - script: |
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - script: ansible-test sanity --python $(python.version) --lint
      displayName: 'Sanity lint'
    - script: ansible-test sanity --python $(python.version) --coverage
      displayName: 'Sanity coverage'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'tests/output/coverage/*'
        testRunTitle: 'Publish test results for Python $(python.version)'
