namespace: kgeorgoudis
name: sftp_client
version: 1.0.2
readme: README.md
authors:
- Konstantinos Georgoudis <kgeorgoudis@icloud.com>
description: sftp client collection
license:
- GPL-3.0-or-later
tags:
  - kgeorgoudis
  - sftp_client
  - sftp
  - paramiko
dependencies: {}
repository: https://github.com/kgeorgoudis/sftp_client
documentation: https://github.com/kgeorgoudis/sftp_client/blob/main/README.md
homepage: https://github.com/kgeorgoudis/sftp_client
issues: https://github.com/kgeorgoudis/sftp_client/issues
build_ignore:
  - build
